language: cpp
dist: xenial

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.2-xenial
  - sudo apt-get -y update

install:
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install -y qt511base qt511declarative

before_script:
  - QTDIR="/opt/qt511"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt511/bin/qt511-env.sh

script:
  - mkdir build && cd build
  - cmake .. && make && ./ProjectElf -v && CTEST_OUTPUT_ON_FAILURE=1 GTEST_COLOR=1 make test
