version: 1.0.{build}

image: Visual Studio 2015
configuration: Debug
platform: x64

environment:
  QTDIR: C:\Qt\5.11.2\mingw53_32

install:
  - set PATH=%PATH%;%QTDIR%\bin
  - set PATH=C:\Qt\Tools\mingw530_32;%PATH%
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -G"CodeBlocks - MinGW Makefiles" ..

build_script:
  - mingw32-make

test_script:
  - mingw32-make test